### ISSUE TITLE
Why could not load mediaLib accelerator wrapper classes?

### ISSUE THREAD

**Issue by gaozhilai** [grzegorzgajda/dicom-viewer#2]
How to resolve this error? please help me. I'm dying,aaaaaaa
Error: Could not load mediaLib accelerator wrapper classes. Continuing in pure Java mode.
Occurs in: com.sun.media.jai.mlib.MediaLibAccessor
com.sun.media.jai.mlib.MediaLibLoadException

**Comment by greg-gajda** [comment]
It's about the availability of JAI native libraries.
You have to download and install version which is appropriate for your platform.

**Comment by gaozhilai** [comment]
I put jai_codec-1.1.3 in my libs,but it's not work.
I use your MPR modul (thank you very much),but the function is token too much time,i can't find the reason,so i doubt the error is the reason,can you give me a way to reduce time.
I speak english not well,sorry,thank you again.

**Comment by greg-gajda** [comment]
Maybe you should try to follow the official docs: http://www.oracle.com/technetwork/java/install-1-1-141405.html

**Comment by gaozhilai** [comment]
This project is very helpful for me,thank you very much!
