### ISSUE TITLE
Curved MPR

### ISSUE THREAD

**Issue by NicolasRannou** [grzegorzgajda/dicom-viewer#3]
Is the demo for curved MPR available somewhere?

**Comment by greg-gajda** [comment]
It's still there: http://www.dicom-viewer.eu
Just select any TK or MR study and then go to MPR (orthogonal or oblique).

**Comment by NicolasRannou** [comment]
How do you go to MPR? :)

thanks!

**Comment by greg-gajda** [comment]
Menu on top-right side of the page

**Comment by NicolasRannou** [comment]
OK I see it now - sorry to botherbut I do not quite see how to use it
![screen shot 2018-01-19 at 9 56 24 am](https://user-images.githubusercontent.com/214063/35142605-0ad394de-fcff-11e7-99ef-1bd27488dd6e.png)

**Comment by NicolasRannou** [comment]
OK I think I got it - I draw line segments and it shows up.

Is that the curved MPR?
![screen shot 2018-01-19 at 9 59 53 am](https://user-images.githubusercontent.com/214063/35142741-8778eff2-fcff-11e7-807f-4fdc93bf6834.png)

**Comment by greg-gajda** [comment]
It's not very smooth curve but you can call it this way.
Just add some more points.

**Comment by NicolasRannou** [comment]
thanks!

**Comment by mmohalil** [comment]
please is demo site still working ..?

**Comment by greg-gajda** [comment]
> please is demo site still working ..?

Unfortunately it's no longer available. 
I may create some terraform code needed to deploy the whole thing on aws, but it's hard to say when I'm going to find enough time.

**Comment by mmohalil** [comment]
thanks for your fast repaly ,
but i cannot understand how to integrate this modules and viewer within DCM4CHEE .
i already have  a working instance of DCM4CHEE with weasis and DWV viewers 
but i need the curved MPR feature .
SO, is this project is an addon for the weasis viewer 
or it is a stand alone viewer to be integrate with DCM4CHEE

I really appreciate your response

**Comment by greg-gajda** [comment]
> is this project is an addon for the weasis viewer
> or it is a stand alone viewer to be integrate with DCM4CHEE

MPR module was intended to be standalone.
